name: Vehicle Expiry Alert Check

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-alert-check:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger secure cron endpoint
        run: |
          curl -L "${{ secrets.CRON_URL }}"
